# Generated by Django 5.1.1 on 2024-09-26 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
    ]
