# Generated by Django 5.1.1 on 2024-09-23 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_product_created_at_alter_product_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
