# Generated by Django 5.1.1 on 2024-09-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_product_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='banner',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
